version: '1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    command: npm run start:migrate:prod
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:    
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - .postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres: